name: geodetic-ffi
channels:
  - conda-forge
dependencies:
  - python=3.14
  - numpy=2.3.4
  - scipy=1.16.2
  - matplotlib=3.10.7
  - xarray=2025.10.1
  - pyproj=3.7.2
  - pygmt=0.17.0
  - psutil=7.1.1
